Shop/ViewModels/CarsListViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;
using System.ComponentModel;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    { 
        public IEnumerable<Car> allCars { get; set; }
        public string currCategory { get; set; }
    }
}

Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System.Collections.Generic;
using System.ComponentModel;

namespace Shop.ViewModels
{
	public class HomeViewModel
	{
		public IEnumerable<Car> favCars { get; set; }
	}
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Shop.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories; 

        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
        {
            _allCars = iAllCars;
            _allCategories = iCarsCat;
        }
        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            var cars = new List<Car>();
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.id).ToList();
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Электромобили")).OrderBy(i => i.id).ToList();
                    currCategory = "Электромобили";
                }
                
                else if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Классические автомобили")).OrderBy(i => i.id).ToList();
                    currCategory = "Классические автомобили";
                }

                

            }
            var carObj = new CarsListViewModel
            {
                allCars = cars,
                currCategory = currCategory
            };
           
            ViewBag.Title = "Страница с автомобилями";
            
            return View(carObj);
            
        }
    }

}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.ViewModels;

namespace Shop.Controllers
{
	public class HomeController : Controller
	{
        private readonly IAllCars _carRep;
        

        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
           
        }
        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _carRep.getFavCars
            };
            return View(homeCars);
        }
    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.interfaces;
using Shop.Data.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allorders, ShopCart shopCart)
        {
            this.allOrders = allorders;
            this.shopCart = shopCart;
        }
        public IActionResult Checkout() {

            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if(shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары!");
            }

            if (ModelState.IsValid)
            {
                allOrders.CreateOrders(order);
                return RedirectToAction("Complete");

            }
            return View();
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    } 


    
    
                 
}

Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System.Linq;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;


        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel { shopCart = _shopCart };

            return View(obj);
        }
            
        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Cars/List.cshtml
@model CarsListViewModel
     <h1>Все автомобили</h1>
     <h3>@Model.currCategory</h3>
     <div class="row mt-5 mb-2" >
         @{
             foreach (Car car in Model.allCars){
                  @Html.Partial("AllCars", car)
             }
             
         }
     </div>
     

Shop/Views/Home/Index.cshtml
@using Shop.Data.Models
@using Shop.ViewModels
@model HomeViewModel


     <h1>Лучшие автомобили</h1>
       <div class="row mt-5 mb-2" >
         @{
             foreach (Car car in Model.favCars){
                  @Html.Partial("AllCars", car)
             }
             
         }
     </div>

Shop/Views/Order/Checkout.cshtml
@model Order 

<div class="row">
	<h3>Оформление заказа</h3>
	<form asp-action="Checkout" method="post" class="form-horizontal">
		<div class="form-group">
		   <label asp-for="name"></label> 
		     <div class="col-md-5">
               <input asp-for="name" class="form-control" /> 
		       <span asp-validation-for="name" class="text-danger"></span>
		     </div>
		</div>
		<div class="form-group">
			<label asp-for="surname"></label>
			<div class="col-md-5">
				<input asp-for="surname" class="form-control" />
				<span asp-validation-for="surname" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="adress"></label>
			<div class="col-md-5">
				<input asp-for="adress" class="form-control" />
				<span asp-validation-for="adress" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="phone"></label>
			<div class="col-md-5">
				<input asp-for="phone" class="form-control" />
				<span asp-validation-for="phone" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="email"></label>
			<div class="col-md-5">
				<input asp-for="email" class="form-control" />
				<span asp-validation-for="email" class="text-danger"></span>
			</div>
		</div>
		<input class="btn btn-success" type="submit" value="Завершить заказ" />
	</form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Shared/AllCars.cshtml
@model Car
<div class="col-lg-4">
	
    <h1 class="display-4">@Model.name</h1>
    <img style="width:350px; height:232px;" src=@Model.img />
    <p class="alert alert-primary" role="alert" style="width:350px;">@Model.shortDesc</p>
    <p>Цена:<span style="color:indianred;font-size:20px;font-weight:20px"> @Model.price.ToString("c")</span></p>
   
    <p><a class="btn btn-info" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Автомобили</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark  bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><ya-tr-span data-index="0-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Kirov Cars" data-ch="0" data-type="trSpan">Kaluga Cars</ya-tr-span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index"><ya-tr-span data-index="1-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Home" data-translation="Главная" data-ch="0" data-type="trSpan">Главная</ya-tr-span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/Cars/List"><ya-tr-span data-index="2-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Link" data-translation="Ссылка" data-ch="0" data-type="trSpan">Машины</ya-tr-span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/Cars/List/electro">Электро</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/Cars/List/fuel">Бензиновые</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Найти" aria-label="Поиск">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-50">

        @RenderBody()
        
    </div>
    <footer class="container mt-5">
        <p class="float-end"><a href="#"><ya-tr-span data-index="26-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Back to top" data-translation="Наверх" data-ch="0" data-type="trSpan">Back to top</ya-tr-span></a></p>
        <p><ya-tr-span data-index="27-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="© 2022 Company, Inc. · " data-translation="© 2022 Компания, Inc. · " data-ch="0" data-type="trSpan" data-selected="false">© 2022 Company, Inc. · </ya-tr-span><a href="#"><ya-tr-span data-index="27-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Privacy" data-translation="Конфиденциальность" data-ch="0" data-type="trSpan" data-selected="false">Privacy</ya-tr-span></a><ya-tr-span data-index="27-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value=" · " data-translation=" · " data-ch="0" data-type="trSpan" data-selected="false"> · </ya-tr-span><a href="#"><ya-tr-span data-index="27-0" data-translated="false" data-source-lang="en" data-target-lang="ru" data-value="Terms" data-translation="Условия" data-ch="0" data-type="trSpan" data-selected="false">Terms</ya-tr-span></a></p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">

	@foreach(var el in Model.shopCart.listShopItems) {

		<div class="alert alert-warning mt-4">
			<b>Автомобиль: </b> @el.car.name<br />
			<b>Цена:</b> @el.car.price.ToString("c")
		</div>
	}
	<hr />
	<a  class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Оплатить</a>


</div>